// Source: Evan's original Entrepreneur Reach Out List. Keep this separate from active HighLevel pipeline contacts.
export const OUTREACH_POOL = [
  {
    "id": "outreach-001",
    "name": "Penny Fitzgerald",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-002",
    "name": "Ahmie-Woma Farkas",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-003",
    "name": "Gina Berry Crawmer",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-004",
    "name": "Ashley Hambell Parrish",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "hosted wine tastings many times",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-005",
    "name": "Laura Smith",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-006",
    "name": "Stephanie Keenan Re",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-007",
    "name": "Stacy Koelle Isbell",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-008",
    "name": "Troy Kuntz",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-009",
    "name": "Jill Flynn",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-010",
    "name": "Liz Shuck-Wojdyla",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-011",
    "name": "Evan Edelmayer",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-012",
    "name": "Jennifer Johnson",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-013",
    "name": "Maria Ofelia Massa-Berry",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "I think?? I honestly cant remember but the name rings a bell",
    "alreadyContacted": false,
    "recommendationStatus": "Needs Review",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-014",
    "name": "Rene Sims",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-015",
    "name": "Amy Smith",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-016",
    "name": "Ashley Anne",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "hosted many tastings",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-017",
    "name": "Heather Kes",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-018",
    "name": "Stephanie Michaels Brown",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-019",
    "name": "Renee Geier",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-020",
    "name": "Tracy Hoover Messner",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-021",
    "name": "Lori Stryker",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-022",
    "name": "Jessica Lyn Godfrey",
    "contactSource": "Wine / Tastings",
    "professionalRole": "worked for corporate",
    "notes": "worked for corporate",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-023",
    "name": "Amanda White",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-024",
    "name": "Michelle Beathard",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-025",
    "name": "Katie Crawford Mathson",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-026",
    "name": "Tracie Bingham",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-027",
    "name": "Pamela Frank-Hall",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-028",
    "name": "Alicia James",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-029",
    "name": "Traci Hinkel Gesell",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-030",
    "name": "Heidi Winslow",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-031",
    "name": "Kimberly Grace",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-032",
    "name": "Milissa MaGee",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "anti MLM now",
    "alreadyContacted": false,
    "recommendationStatus": "Do Not Recommend",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-033",
    "name": "Lesa Viducich Brinker",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-034",
    "name": "Olivia Domingues",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-035",
    "name": "Julie Kick",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "works for Allison's travel group",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-036",
    "name": "Nicole Wenzel",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-037",
    "name": "Kim Courtney",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-038",
    "name": "Jonelle Spiker",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "works for Allisons travel group",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-039",
    "name": "Jeffery Jurist",
    "contactSource": "Wine / Tastings",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-040",
    "name": "Jordanne Menzies",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-041",
    "name": "Molly Haskins",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "Top Level Leader",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-042",
    "name": "Tyler Barnes",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "customer",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-043",
    "name": "Dawon Webb",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "sampled",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-044",
    "name": "Chris Atwood",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-045",
    "name": "Jayson Stewart",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "top level leader",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-046",
    "name": "Dominic Colby",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "customer",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-047",
    "name": "Dara Bose",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "I think",
    "alreadyContacted": false,
    "recommendationStatus": "Needs Review",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-048",
    "name": "Jamie Margraf",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-049",
    "name": "Tracy Erin",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-050",
    "name": "Aaron Aponte",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-051",
    "name": "Michael Alexander",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "customer",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-052",
    "name": "Jennifer Lipe",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-053",
    "name": "Dennis Carnahan",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "leader",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-054",
    "name": "Loretta Acker",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-055",
    "name": "Teri Taylor",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-056",
    "name": "Terry Lynne randall Sanford",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-057",
    "name": "Eric Sablan",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "already sampled-- wanted to create a partnership but never heard back from him.",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-058",
    "name": "Fabian Brown",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-059",
    "name": "Phil Brown",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-060",
    "name": "David Breedlove",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-061",
    "name": "Robert Ruff",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-062",
    "name": "Dawn Smith",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-063",
    "name": "Heidi Koen",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-064",
    "name": "Deanna Lavada",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-065",
    "name": "Terry Bradly Wilhem",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-066",
    "name": "Cathy Leonard",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "not sure US based",
    "alreadyContacted": false,
    "recommendationStatus": "Needs Review",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-067",
    "name": "Ben Rusk",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-068",
    "name": "Mike Poetkhen",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-069",
    "name": "Marlo Hatfield Hutchings",
    "contactSource": "Le-Vel",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-070",
    "name": "Chris Jakubiak",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "fitness trainer",
    "notes": "fitness trainer",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-071",
    "name": "Pamela Wallentiny",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-072",
    "name": "Natalie Forest",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-073",
    "name": "Karl Vogel",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "realtor",
    "notes": "realtor",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-074",
    "name": "Jon Skrzymowski",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-075",
    "name": "Jeff Meador",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-076",
    "name": "Christoff J Weihman",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-077",
    "name": "Joze Petek",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "not sure if US based",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-078",
    "name": "Lisa Winfield",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "personal success coach",
    "notes": "personal success coach",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-079",
    "name": "Kerrin Black",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-080",
    "name": "Tony Beard",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "yoga instructor",
    "notes": "yoga instructor",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-081",
    "name": "Michael Elder",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "massage therapist",
    "notes": "massage therapist",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-082",
    "name": "Terry F Kraus",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "realtor",
    "notes": "realtor",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-083",
    "name": "Jo Wilkens",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-084",
    "name": "Tasha Tillman",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "MLM",
    "notes": "MLM",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-085",
    "name": "Elizabeth Patrick",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-086",
    "name": "Kaylan Wetzel Spinola",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-087",
    "name": "Ava Boudi",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-088",
    "name": "David Ayala",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-089",
    "name": "Daniela Roman",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-090",
    "name": "Kemone Hendricks",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-091",
    "name": "Elizabeth Carey Thompson",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-092",
    "name": "Stefaan De Vreese",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "not sure if US based but has US customers I assume",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-093",
    "name": "Christa Rose",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-094",
    "name": "Renee Barricklow Frampton",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-095",
    "name": "Nikki G Glemaud",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-096",
    "name": "Ty Mccarthy",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "fitness",
    "notes": "fitness",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-097",
    "name": "Dionne Roberts",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "not US based",
    "alreadyContacted": false,
    "recommendationStatus": "Needs Review",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-098",
    "name": "Mel Mason",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-099",
    "name": "Teresa Campos",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-100",
    "name": "Robert J App",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-101",
    "name": "Shadoe Bella Gray",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-102",
    "name": "Kyle Thomas",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "astrologer",
    "notes": "astrologer",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-103",
    "name": "Emily Gollmer",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-104",
    "name": "Jeno Singson",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-105",
    "name": "Kristi Battalini",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-106",
    "name": "Patrick Klein",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-107",
    "name": "Amy Grussing",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-108",
    "name": "Kit Tin W-Volcano",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-109",
    "name": "Jacques Skuteeki",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "not sure US based",
    "alreadyContacted": false,
    "recommendationStatus": "Needs Review",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-110",
    "name": "Samuel Gegen",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-111",
    "name": "Terry Houze",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-112",
    "name": "Mitchell Levy",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-113",
    "name": "Janet N Love",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-114",
    "name": "Benjamin Ritter",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "self and personal development",
    "notes": "self and personal development",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-115",
    "name": "Brenda Marie Sheldrake",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-116",
    "name": "Stephanie Solovy",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-117",
    "name": "Bryan Akers",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "another wellness company",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-118",
    "name": "Tabren Smith",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "realtor",
    "notes": "realtor",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-119",
    "name": "Tammy Workman-Lopez",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "executive leadership coach",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-120",
    "name": "Krystylle Richardson",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-121",
    "name": "DC Goliath",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-122",
    "name": "Albert Corey",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "accountant",
    "notes": "accountant",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-123",
    "name": "Art Ismy Love",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-124",
    "name": "Elizabeth Frederick",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "creativity consultant",
    "notes": "creativity consultant",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-125",
    "name": "Ursula Akey Vaillancourt",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-126",
    "name": "Janice Eullie-Hodges",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "realtor",
    "notes": "realtor",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-127",
    "name": "Sabrina Protic",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-128",
    "name": "Richard Mathews",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "realtor",
    "notes": "realtor",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-129",
    "name": "Lizzy Montana",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "film",
    "notes": "film",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-130",
    "name": "Jason R Rosenberg",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "realtor",
    "notes": "realtor",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-131",
    "name": "Chris Landano",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-132",
    "name": "CheRhonda Greenlee",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-133",
    "name": "Mommin Itlike Aboss",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-134",
    "name": "Lumbie Mlambo",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-135",
    "name": "Brandon Despras",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-136",
    "name": "Michelle O'Kennard",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "event planning",
    "notes": "event planning",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-137",
    "name": "Everett Cody",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-138",
    "name": "Sara Gilbert-Strategist",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "strategist",
    "notes": "strategist",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-139",
    "name": "Nikki Hallam",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-140",
    "name": "Phil Lolly",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-141",
    "name": "Emilio Roman",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-142",
    "name": "George Cain",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "realtor",
    "notes": "realtor",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-143",
    "name": "Jackson Crisp",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-144",
    "name": "Joseph Federico",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "advertising",
    "notes": "advertising",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-145",
    "name": "Kelly Joy Freeman",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-146",
    "name": "Steve Weiss",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-147",
    "name": "Charles Vest",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-148",
    "name": "Andrea Nicolle",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-149",
    "name": "Julie D'Ann",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-150",
    "name": "Cristian Von Hauser",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-151",
    "name": "Robinson Shelas",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-152",
    "name": "Shari Bush",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-153",
    "name": "Valerie Kelso",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-154",
    "name": "Bridgetti Lim Banda",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "Talkshow host",
    "notes": "Talkshow host",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-155",
    "name": "Edit B Kiss",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-156",
    "name": "Sonia Kurmey",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "arbonne",
    "notes": "arbonne",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-157",
    "name": "Tom DeLuca",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-158",
    "name": "Shellie Hunt",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "Women of Global Change",
    "notes": "Women of Global Change",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-159",
    "name": "Andrew Nathan",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-160",
    "name": "Geoffrey Michaels",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "energy",
    "notes": "energy",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-161",
    "name": "Crystal C Frederick",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "health and wealth coach",
    "notes": "health and wealth coach",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-162",
    "name": "Gabriella Barta",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-163",
    "name": "Justin Dominic Mezetin",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-164",
    "name": "Joanne Canoy",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "event planner",
    "notes": "event planner",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-165",
    "name": "Therea Taylor",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "business coach",
    "notes": "business coach",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-166",
    "name": "Jarius McNair Edens",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "health and life coach, former educator",
    "notes": "health and life coach, former educator",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-167",
    "name": "Elizabeth Harper",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "life coach",
    "notes": "life coach",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-168",
    "name": "William Gavopoulos",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "finance",
    "notes": "finance",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-169",
    "name": "Christopher Hux",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "physical therapist",
    "notes": "physical therapist",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-170",
    "name": "Riccardo Carollo, personal branding",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "unsure if US based",
    "notes": "unsure if US based",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-171",
    "name": "Marty Munoz",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-172",
    "name": "Claudio Pogliari",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "Canada based",
    "notes": "Canada based",
    "alreadyContacted": false,
    "recommendationStatus": "Needs Review",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-173",
    "name": "Catherine Linda Elise Lazure, online business manager",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "Canada based",
    "notes": "Canada based",
    "alreadyContacted": false,
    "recommendationStatus": "Needs Review",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-174",
    "name": "Fade Fernando",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "life skills coach",
    "notes": "life skills coach",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-175",
    "name": "LaurieAnn Campbell",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-176",
    "name": "Micca Lemon",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "nutritionist",
    "notes": "nutritionist",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-177",
    "name": "Kohila Sivas",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "Canada based",
    "notes": "Canada based",
    "alreadyContacted": false,
    "recommendationStatus": "Needs Review",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-178",
    "name": "Sheronte Dirkell",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-179",
    "name": "Haleh Houshim",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "high speed marketing",
    "notes": "high speed marketing",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-180",
    "name": "Andrew Martin",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-181",
    "name": "Eric Caron",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "catering",
    "notes": "catering",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-182",
    "name": "Krysten Maracle",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-183",
    "name": "Alec Meehan",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "funnel builder",
    "notes": "funnel builder",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-184",
    "name": "Dee Bowden",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-185",
    "name": "Jill Thompson Wicke",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "skincare and consulting",
    "notes": "skincare and consulting",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-186",
    "name": "Darryl A Johnson",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "thriving women network and finance",
    "notes": "thriving women network and finance",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-187",
    "name": "George Grant",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-188",
    "name": "Tod Moore",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-189",
    "name": "Lore EnJoli",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "body butter",
    "notes": "body butter",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-190",
    "name": "Julie Sias Page",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-191",
    "name": "Arthur Carr Jr",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-192",
    "name": "Nancy Evans",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "wellness consultant",
    "notes": "wellness consultant",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-193",
    "name": "Ruth Wilson",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-194",
    "name": "Lucretia Barraco-Martinello",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-195",
    "name": "Peter DeWitt",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "gay wellness",
    "notes": "gay wellness",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-196",
    "name": "Kris Tyler",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-197",
    "name": "Thomesa Lydon",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-198",
    "name": "Eric Gaudet",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "not entrepreneur, but an RN",
    "notes": "not entrepreneur, but an RN",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-199",
    "name": "Jacalyn Price",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "no US based",
    "notes": "no US based",
    "alreadyContacted": false,
    "recommendationStatus": "Needs Review",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-200",
    "name": "Shirley Caldwell Ross",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-201",
    "name": "Sharon JB Mefford",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-202",
    "name": "Katia N Miller Pagan",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-203",
    "name": "Angela Howard",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-204",
    "name": "Wendy Musch",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-205",
    "name": "Debbie Dusek",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-206",
    "name": "Eric Konovalov",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-207",
    "name": "Denise Vargas",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-208",
    "name": "Shanna Lee Moore",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "massage therapist & developing true health",
    "notes": "massage therapist & developing true health",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-209",
    "name": "Kristina Tickler Welsome",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-210",
    "name": "Liza Boubari",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "founder heal within",
    "notes": "founder heal within",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-211",
    "name": "Jeff House",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-212",
    "name": "Steven Thomas Daniel",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-213",
    "name": "Kim Emery-Poulin",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-214",
    "name": "Karlton Hoskins",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-215",
    "name": "Diana Zwein",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "WFG",
    "notes": "WFG",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-216",
    "name": "Kayla Becker",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "success coach",
    "notes": "success coach",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-217",
    "name": "Dave Mcr",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "rugby",
    "notes": "rugby",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-218",
    "name": "Tony Odisho",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "salon and haircare owner",
    "notes": "salon and haircare owner",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-219",
    "name": "Lisa Khera",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-220",
    "name": "Shawn Duteil",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "coaching",
    "notes": "coaching",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-221",
    "name": "Kimberly Hale",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-222",
    "name": "Moe Abbassi",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-223",
    "name": "Mary Elizabeth jackson",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "talkshow host",
    "notes": "talkshow host",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-224",
    "name": "Susan Levin",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-225",
    "name": "Cettina Rita Farruggia",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-226",
    "name": "Nicolas Lee",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-227",
    "name": "DrNiti Solomon",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-228",
    "name": "DrCollette Portis",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-229",
    "name": "Joshua Ivy",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "again not entrepreneur but RN",
    "notes": "again not entrepreneur but RN",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-230",
    "name": "Michelle Oliver",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-231",
    "name": "Erick Gadea-Sanchez",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "health coach",
    "notes": "health coach",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-232",
    "name": "Nikki Hale",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "consulting",
    "notes": "consulting",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-233",
    "name": "Shona Aime",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "fitness",
    "notes": "fitness",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-234",
    "name": "Marcus Howard",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-235",
    "name": "Andy Boyer",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "massage therapist",
    "notes": "massage therapist",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-236",
    "name": "DrTuere Harrold",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "realtor",
    "notes": "realtor",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-237",
    "name": "Melody Johnson",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-238",
    "name": "Joni Rials",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-239",
    "name": "Angele Rochin",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "optivia",
    "notes": "optivia",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-240",
    "name": "Jane Warr",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-241",
    "name": "Shreya Kumar-Thakur",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-242",
    "name": "Erik Toth",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "marketing",
    "notes": "marketing",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-243",
    "name": "Cheri Nabat Shuman",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "consulting",
    "notes": "consulting",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-244",
    "name": "Darcy Dietz-Fenoglio",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-245",
    "name": "Ann Landstrom",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "photography",
    "notes": "photography",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-246",
    "name": "Catalina Grija",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-247",
    "name": "Sean Triglia",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-248",
    "name": "Soe Tun",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-249",
    "name": "Edwin Edebiri",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "happy neighborhood project",
    "notes": "happy neighborhood project",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-250",
    "name": "KJ Vin",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-251",
    "name": "Delores Steele",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-252",
    "name": "John Sporing",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "chief taster at a life well drunk",
    "notes": "chief taster at a life well drunk",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-253",
    "name": "DrKatrina Esau",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-254",
    "name": "Chuck LaDouceur",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "marketing",
    "notes": "marketing",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-255",
    "name": "Keysha Truss Chester",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-256",
    "name": "Missa Capozzo",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "former wine and now fitness",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-257",
    "name": "Joseph Carty",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-258",
    "name": "Alison McMaster, masterfully planned experiences",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "travel agency mentioned",
    "notes": "travel agency mentioned",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-259",
    "name": "Louis Agius",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-260",
    "name": "Lynette Trumper",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-261",
    "name": "Jose J Elizondo",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "marketing",
    "notes": "marketing",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-262",
    "name": "DrTajiri Brackens",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "coaching",
    "notes": "coaching",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-263",
    "name": "Leslie Klein",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-264",
    "name": "Romy Faith Ganser",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-265",
    "name": "DrTamara Bowles",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-266",
    "name": "Armin Shafee",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-267",
    "name": "Anne Mary",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-268",
    "name": "Lovie AndMe",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-269",
    "name": "Saul Davila",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "also an RN",
    "notes": "also an RN",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-270",
    "name": "Jill Wright",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-271",
    "name": "Jessica Johnson",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-272",
    "name": "Bhavna Sriastava",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "wellness",
    "notes": "wellness",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-273",
    "name": "Claudia Kaltenstadler",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-274",
    "name": "Rick Rood",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "former teacher coach",
    "notes": "former teacher coach",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-275",
    "name": "Nita Boyd Vogt",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-276",
    "name": "Alka Bailey",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-277",
    "name": "Maribel Colmenares",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-278",
    "name": "Paige Davidson",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-279",
    "name": "Asa Leveaux",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "marketing and coaching",
    "notes": "marketing and coaching",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-280",
    "name": "DrNalo Thomas-Mitchell",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-281",
    "name": "Sonia Clark",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "not US Based",
    "alreadyContacted": false,
    "recommendationStatus": "Needs Review",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-282",
    "name": "Unique Shamque",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-283",
    "name": "Florynce Mathews",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-284",
    "name": "Michelle Griffith davis",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-285",
    "name": "Andru Vergara",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-286",
    "name": "DK Warinner",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-287",
    "name": "Silvia Louro",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-288",
    "name": "Olga Obolonskaya",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-289",
    "name": "Sheron McDow",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "event planner",
    "notes": "event planner",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-290",
    "name": "Dilia Delgado",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "realtor",
    "notes": "realtor",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-291",
    "name": "Luke Lintott",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "yoga and wellness coach",
    "notes": "yoga and wellness coach",
    "alreadyContacted": true,
    "recommendationStatus": "Contacted / Active",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-292",
    "name": "Juan Jorrin",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-293",
    "name": "Bridgett Renay",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-294",
    "name": "Grace Strachan",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "send out cards",
    "notes": "send out cards",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-295",
    "name": "Asma Yousif",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "",
    "notes": "",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-296",
    "name": "Shikilia Caro",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "real estate",
    "notes": "real estate",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-297",
    "name": "Naomi Jones",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "retired RN",
    "notes": "retired RN",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-298",
    "name": "Marilyn A Chivetta",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "paparazzi jewelry",
    "notes": "paparazzi jewelry",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-299",
    "name": "Deb Oberlander",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "mary kay",
    "notes": "mary kay",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-300",
    "name": "Wendy Talley",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "mental health consulting",
    "notes": "mental health consulting",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-301",
    "name": "Paul Andres Trudel-Payne",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "mental health",
    "notes": "mental health",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-302",
    "name": "Tracy Simpson Wheeler",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "spa",
    "notes": "spa",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  },
  {
    "id": "outreach-303",
    "name": "Jerry Scarlato",
    "contactSource": "Entrepreneur Network",
    "professionalRole": "fitness",
    "notes": "fitness",
    "alreadyContacted": false,
    "recommendationStatus": "Ready for First Reach-Out",
    "stage": "Reach Out",
    "lastRecommendedDate": ""
  }
];

